server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.104.69.163:3306/lovetime?serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#定义一个全局的编码格式。(可以使用快捷键 alt)
  http:
    encoding:
      charset: UTF-8
      force: true
      force-request: true
      enabled: true